//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCare_4_0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PI_Domain_Prd {
            get {
                return ((string)(this["PI_Domain_Prd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIRIPI")]
        public string PI_User_Prd {
            get {
                return ((string)(this["PI_User_Prd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sansiri")]
        public string PI_Pwd_Prd {
            get {
                return ((string)(this["PI_Pwd_Prd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xidev:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_CRM" +
            "_WEB_SERVICE&receiverParty=&receiverService=&interface=Z_SI_ADVANCE_VENDOR&inter" +
            "faceNamespace=http%3A%2F%2Fwww.sansiri.com%2FCRM%2Fadvance")]
        public string HomeCare_4_0_SAP_HC_XI_ff07ed6e42ac32019d0af43160bf618e_Service {
            get {
                return ((string)(this["HomeCare_4_0_SAP_HC_XI_ff07ed6e42ac32019d0af43160bf618e_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xiqas.sansiri.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BC_VENDOR_MANAGEMENT_WEB_SERVICE&receiverParty=&receiverService=&interface" +
            "=SI_Vendor_Search_Sync_Req&interfaceNamespace=http%3A%2F%2Fwww.sansiri.com%2FECC" +
            "%2FVENDOR%2F")]
        public string HomeCare_4_0_SI_Vendor_Search_Sync_Req_SI_Vendor_Search_Sync_ReqService {
            get {
                return ((string)(this["HomeCare_4_0_SI_Vendor_Search_Sync_Req_SI_Vendor_Search_Sync_ReqService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.siriintranet.com/eleave/Service/webServiceGetLeave.asmx")]
        public string HomeCare_4_0_WebServiceGetLeave_webServiceGetLeave {
            get {
                return ((string)(this["HomeCare_4_0_WebServiceGetLeave_webServiceGetLeave"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("API/Calendar/GetHCCalendarList")]
        public string CareSyncOutlookAPI {
            get {
                return ((string)(this["CareSyncOutlookAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mobile.sansiri.com/moaserver/PushService.asmx")]
        public string HomeCare_4_0_PushService_PushService {
            get {
                return ((string)(this["HomeCare_4_0_PushService_PushService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://20.20.20.38/homecare_api/")]
        public string Hostapi {
            get {
                return ((string)(this["Hostapi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xidev:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_CRM" +
            "_WEB_SERVICE&receiverParty=&receiverService=&interface=Z_SI_ADVANCE_VENDOR&inter" +
            "faceNamespace=http%3A%2F%2Fwww.sansiri.com%2FCRM%2Fadvance")]
        public string HomeCare_4_0_SAP_HC_XI_ff07ed6e42ac32019d0af43160bf618e_Service1 {
            get {
                return ((string)(this["HomeCare_4_0_SAP_HC_XI_ff07ed6e42ac32019d0af43160bf618e_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xiqas.sansiri.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BC_VENDOR_MANAGEMENT_WEB_SERVICE&receiverParty=&receiverService=&interface" +
            "=SI_Vendor_Search_Sync_Req&interfaceNamespace=http%3A%2F%2Fwww.sansiri.com%2FECC" +
            "%2FVENDOR%2F")]
        public string HomeCare_4_0_SI_Vendor_Search_Sync_Req_SI_Vendor_Search_Sync_ReqService1 {
            get {
                return ((string)(this["HomeCare_4_0_SI_Vendor_Search_Sync_Req_SI_Vendor_Search_Sync_ReqService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mobile-dev.sansiri.com/moaserverqas/PushService.asmx")]
        public string HomeCare_4_0_PushService_PushService1 {
            get {
                return ((string)(this["HomeCare_4_0_PushService_PushService1"]));
            }
        }
    }
}
