//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCare_4_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_TM_SpecL3
    {
        public int id { get; set; }
        public string name { get; set; }
        public int specL2_id { get; set; }
        public int priority_id { get; set; }
        public bool active { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime updated_date { get; set; }
        public string updated_by { get; set; }
    }
}
