//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCare_4_0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LogAppEntities : DbContext
    {
        public LogAppEntities()
            : base("name=LogAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int usp_homeservice_SaveLog_WS(string service_Name, string description, Nullable<System.DateTime> requestTime, Nullable<System.DateTime> responseTime, string return_Code, string return_Message, string input_Param, string output_Data, string query, string hostName, string iPAddress, Nullable<long> referenceId, string referenceId_All)
        {
            var service_NameParameter = service_Name != null ?
                new ObjectParameter("Service_Name", service_Name) :
                new ObjectParameter("Service_Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var requestTimeParameter = requestTime.HasValue ?
                new ObjectParameter("RequestTime", requestTime) :
                new ObjectParameter("RequestTime", typeof(System.DateTime));
    
            var responseTimeParameter = responseTime.HasValue ?
                new ObjectParameter("ResponseTime", responseTime) :
                new ObjectParameter("ResponseTime", typeof(System.DateTime));
    
            var return_CodeParameter = return_Code != null ?
                new ObjectParameter("Return_Code", return_Code) :
                new ObjectParameter("Return_Code", typeof(string));
    
            var return_MessageParameter = return_Message != null ?
                new ObjectParameter("Return_Message", return_Message) :
                new ObjectParameter("Return_Message", typeof(string));
    
            var input_ParamParameter = input_Param != null ?
                new ObjectParameter("Input_Param", input_Param) :
                new ObjectParameter("Input_Param", typeof(string));
    
            var output_DataParameter = output_Data != null ?
                new ObjectParameter("Output_Data", output_Data) :
                new ObjectParameter("Output_Data", typeof(string));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            var hostNameParameter = hostName != null ?
                new ObjectParameter("HostName", hostName) :
                new ObjectParameter("HostName", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var referenceIdParameter = referenceId.HasValue ?
                new ObjectParameter("ReferenceId", referenceId) :
                new ObjectParameter("ReferenceId", typeof(long));
    
            var referenceId_AllParameter = referenceId_All != null ?
                new ObjectParameter("ReferenceId_All", referenceId_All) :
                new ObjectParameter("ReferenceId_All", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_homeservice_SaveLog_WS", service_NameParameter, descriptionParameter, requestTimeParameter, responseTimeParameter, return_CodeParameter, return_MessageParameter, input_ParamParameter, output_DataParameter, queryParameter, hostNameParameter, iPAddressParameter, referenceIdParameter, referenceId_AllParameter);
        }
    }
}
