//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCare_4_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_V_UserAcct
    {
        public long ID { get; set; }
        public string NameCode { get; set; }
        public string firstName { get; set; }
        public string firstNameTH { get; set; }
        public string lastName { get; set; }
        public string lastNameTH { get; set; }
        public string NameENG { get; set; }
        public string NameTH { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_NameCode { get; set; }
        public string Dept_NameENG { get; set; }
    }
}
